### ISSUE TITLE
 unrecognized argument: '--bind=' in rundisco.cmd

### ISSUE THREAD

**Issue by ingolfheinsch** [dis-co/disco#27]
### Description

rundico.cmd drops the following error:

```
C:\Disco-0.5.0>Disco\disco.exe start --machine=\Disco\etc --bind=
Fatal: Other error: ERROR: unrecognized argument: '--bind='.
USAGE: disco.exe [--help] [--project=<string>] [--machine=<string>] [--frontend=<string>] <help|start|setup>

CMD:

    <help|start|setup>    Main Command: either one of setup, start, or help.

OPTIONS:

    --project=<string>    Name of project directory in the workspace
    --machine=<string>    Path to the machine config file
    --frontend=<string>   Path to the frontend files
    --help                display this list of options.
 in Main
```

### HowTo Reproduce

start the rundisco.cmd 

### Expected and actual results

Please provide the expected and actual results.

### Related information

* Disco Version: 0.5.0
* RunTime Version:
* Operating system:

**Comment by krgn** [comment]
The wrapper scripts are due to be removed and not recommended to use. Please use 

`disco.exe setup` 

to create a new machine configuration file, followed by 

`disco.exe start`

to start the daemon.
