### ISSUE TITLE
could not find machine configuration

### ISSUE THREAD

**Issue by ingolfheinsch** [dis-co/disco#28]
### Description
there is no machine configuration if you start disco the first time.
```
NSYNK@MISCHA : C:\Disco-0.5.0\Disco : PS>.\disco.exe start --machine=\Disco\etc
Fatal: IO Error: could not find machine configuration in MachineConfig.load
```

### HowTo Reproduce

.\disco.exe start --machine="\Disco\etc" --frontend="YOUR IP"

### Expected and actual results

DISCO should create new machine config automatically if it cant find any

### Related information

* Disco Version: 0.5.0
* RunTime Version:
* Operating system:

**Comment by krgn** [comment]
You have to create a new machine configuration file (`machinecfg.yaml`). This is now done by invoking:

`disco.exe setup` 

and following the instructions (default values are chosen by pressing `Enter`).
