### ISSUE TITLE
infinite message loop in cluster

### ISSUE THREAD

**Issue by ingolfheinsch** [dis-co/disco#31]
### Description

if pinvalues got changed in cluster environment (2 Machines here) DISCO Service produces an infinity message loop
the receiving client is re-sending message

### HowTo Reproduce

create a project with at least 2 machines running in a  cluster and change any pinvalue

### Expected and actual results

the receiving client should not re-send any pinvalues

### Related information

* Disco Version: 0.1.0
* RunTime Version:
* Operating system:

**Comment by krgn** [comment]
This problem was fixed in #42 and the fix will be available v0.1.1
