### ISSUE TITLE
help patch for the graph api

### ISSUE THREAD

**Issue by ingolfheinsch** [dis-co/disco#32]
### Description

Please provide a help patch for the graph api

### HowTo Reproduce

Please provide as much information how to reproduce this issue as
possible, including stack traces, versions/commit/tag used etc.

### Expected and actual results

Please provide the expected and actual results.

### Environment information

* Disco Version:
* Member Count:
* Type of Client:

### Related information

* RunTime Version:
* Operating system:

**Comment by krgn** [comment]
If you have one, please put it [here](https://github.com/dis-co/disco/tree/master/vvvv/modulesl) and a PR :)

**Comment by krgn** [comment]
@ingolfheinsch I guess you added a patch, shall we close?

**Comment by krgn** [comment]
this was added in #53
