### ISSUE TITLE
start with project argument fails after IP change

### ISSUE THREAD

**Issue by ingolfheinsch** [dis-co/disco#37]
### Description

after chaching IP of the host i got the following error if i try start existing project with --project argument
`Fatal: Project error: Missing member: 72771240-054e-4739-8252-d86a038ca82c in Config.findMember`

start without argument forces user to create new Site. afterwards it waorks as expected

### HowTo Reproduce

* create project
* change ip
* run setup
* start disco using --project argument

### Expected and actual results

Please provide the expected and actual results.

### Environment information

* Disco Version: 1.0.1
* Member Count: 1
* Type of Client: -

### Related information

* RunTime Version:
* Operating system:

**Comment by krgn** [comment]
We'll need to have a way of automatically creating a new cluster site containing the current member. We can do that, but the `--project` option is mostly used for automated start in more "deterministic" environments (e.g. where the IP setup if fixed)

**Comment by ingolfheinsch** [comment]
k. see. but then it should output some hint to the user like "need to create new cluster site" as the error message means not much to an end user
