### ISSUE TITLE
empty workspace in remote session

### ISSUE THREAD

**Issue by ingolfheinsch** [dis-co/disco#39]
### Description

if i conect to frontend-service through a remote session the workspace is empty while it should show the project related widgets.

### HowTo Reproduce

* create project
* put some widgets onto the workspace
* save project
* connect to IP:7000 from another browser or from a remote computer

### Expected and actual results

it should show the same view with all open widgets

### Environment information

* Disco Version: 1.0.1
* Member Count: 1
* Type of Client: vvvv

### Related information

* RunTime Version:
* Operating system:

**Comment by krgn** [comment]
Currently, layouts are persisted to the local browser storage and are not part of the project (yet). This is a planned feature though. Closing.
