### ISSUE TITLE
"Adress already in use" after Setup

### ISSUE THREAD

**Issue by ingolfheinsch** [dis-co/disco#43]
### Description

after running setup i got the following message:
```
loading configuration from: "C:\Disco-0.1.1\disco\etc\machinecfg.yaml"
Fatal: Address 192.168.2.50:7000 already in use
```

### HowTo Reproduce

* download and setup version 0.1.0
* download and setup version 0.1.1

### Expected and actual results

Please provide the expected and actual results.

### Environment information

* Disco Version: 0.1.1
* Member Count:
* Type of Client:

### Related information

* RunTime Version:
* Operating system:

**Comment by krgn** [comment]
I don't understand yet what the exact procedure is you were using to get to that error. Could give some more detail, possibly by pasting the respective sequence of commands?

**Comment by ingolfheinsch** [comment]
seems i just chose an adapter with no cable connected
