### ISSUE TITLE
wrong vvvv client directory structure

### ISSUE THREAD

**Issue by ingolfheinsch** [dis-co/disco#44]
### Description

the vvvv client directory structure should look like this:

..\clients\vvvv\nodes\modules
..\clients\vvvv\nodes\plugins

### HowTo Reproduce

Please provide as much information how to reproduce this issue as
possible, including stack traces, versions/commit/tag used etc.

### Expected and actual results

Please provide the expected and actual results.

### Environment information

* Disco Version:
* Member Count:
* Type of Client:

### Related information

* RunTime Version:
* Operating system:

**Comment by krgn** [comment]
Should work now and be available in a forthcoming build
