### ISSUE TITLE
remove user login

### ISSUE THREAD

**Issue by ingolfheinsch** [dis-co/disco#46]
### Description

to speed up testing i would suggest to temporary remove user log-in screen as it isnt doing anything useful at the moment,

### HowTo Reproduce

Please provide as much information how to reproduce this issue as
possible, including stack traces, versions/commit/tag used etc.

### Expected and actual results

Please provide the expected and actual results.

### Environment information

* Disco Version:
* Member Count:
* Type of Client:

### Related information

* RunTime Version:
* Operating system:

**Comment by krgn** [comment]
I can't reproduce this behavior in current master. What were the exact steps you took? I had no project in that machine's workspace, so I was prompted to enter a new project name. (That dialog still pops up one more time during project loading, which needs to be solved eventually)
