### ISSUE TITLE
IO-Box configurations are ignored

### ISSUE THREAD

**Issue by ingolfheinsch** [dis-co/disco#47]
### Description

the io box value [min, max] constraints which are set in vvvv client are ignored by the front end

### HowTo Reproduce
expose value io box and set value [min, max] contraints to [0,1] . the open graph view and change the value. the contraint is being ignored

### Expected and actual results

value change in front end should only be able in the given range.

### Environment information

* Disco Version: 1.0.1
* Member Count: 1
* Type of Client: vvvv

### Related information

* RunTime Version:
* Operating system:

**Comment by ingolfheinsch** [comment]
it seems that none of the io-box settings made its way into the front-end. also the value type is ignored (which set to "real"). where the front just set integers

**Comment by krgn** [comment]
Real/Integer/Boolean type parsing and display works, I just verified it. You might need to unexpose the IOBox, set to the desired behavior and re-expose it in order for that to work. The min/max issue is resolved though, so I close.
