### ISSUE TITLE
bang value atom need 2 clicks to work properly

### ISSUE THREAD

**Issue by ingolfheinsch** [dis-co/disco#49]
### Description

the value atom for the vvvv bang io box needs 2 mousclicks where it should work with just one.
as it currently uses toggle behavior the user has to manually reset toggle state by a second click.

### HowTo Reproduce

* create bang io box. click on the value atom in the front end.
* it changes from fals to true but then need to be set to false again manually.

### Expected and actual results

* it should be a one click action.

### Environment information

* Disco Version: 0.1.0
* Member Count: 1 
* Type of Client: vvvv

### Related information

* RunTime Version:
* Operating system:

**Comment by krgn** [comment]
This is a problem that needs to be addressed at the service level, as well as specially handled in VVVV, since the _reset_ event needs to happen in the next frame there. I'll see to this.
