### ISSUE TITLE
unable to change real part of floating point value 

### ISSUE THREAD

**Issue by ingolfheinsch** [dis-co/disco#83]
### Description

its not possible to change the real part of a floating point number in the value atom. it only allow to change the whole part.

### HowTo Reproduce

expose iobox value. set min to 0 and max to something. try to set any floating point value in the browser

### Expected and actual results
press and drag should always change the real part of the number if the exposed value is set to real

### Environment information

* Disco Version: 0.1.3
* Member Count: 1 
* Type of Client: vvvv

### Related information

* RunTime Version:
* Operating system:

**Comment by krgn** [comment]
fixed in #85
